### ISSUE TITLE
Need to import Pet

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-flask-sqlalchemy-pt2#3]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/209741?module_item_id=483939

### Concern

In the **Creating our Views** section, we start using the Pet model in our pet_by_id method. We haven't instructed students to import that model, nor was it included in the imports in the previous example. If we want students to use this opportunity to debug, we might want to make that intentional. I.e. _If you're getting an error, what might we need to include as an import?_. If it's not our intention to have them debug, we should probably tell them to include it as an import.

**Comment by professor-ben** [comment]
I like your debugging idea- I'll try to implement that later.

For now, those imports have been updated in the README.

Thanks,
Ben
